In [1]:
import os

base_path = "."

splits = ["train", "valid", "test"]

for split in splits:
    img_path = os.path.join(base_path, split, "images")
    lbl_path = os.path.join(base_path, split, "labels")
    
    num_images = len(os.listdir(img_path))
    num_labels = len(os.listdir(lbl_path))
    
    print(f"{split.upper()}:")
    print(f"  Images: {num_images}")
    print(f"  Labels: {num_labels}")
    print("-" * 30)

TRAIN:
  Images: 4072
  Labels: 4072
------------------------------
VALID:
  Images: 122
  Labels: 122
------------------------------
TEST:
  Images: 65
  Labels: 65
------------------------------

In [2]:
from collections import Counter

label_dir = "train/labels"
counter = Counter()

for file in os.listdir(label_dir):
    with open(os.path.join(label_dir, file), "r") as f:
        for line in f.readlines():
            class_id = line.split()[0]
            counter[class_id] += 1

print("Class distribution in TRAIN:")
print(counter)

Class distribution in TRAIN:
Counter({'0': 6696, '1': 567})

In [3]:
from ultralytics import YOLO

model = YOLO("yolov8n.pt")

model.train(
    data="data.yaml",
    epochs=10,        # small test
    imgsz=416,       # reduce image size
    batch=4,         # reduce batch
    workers=0        # avoid RAM overload
)

Ultralytics 8.4.15  Python-3.14.3 torch-2.10.0+cpu CPU (AMD Ryzen 7 7840HS w/ Radeon 780M Graphics)
engine\trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=4, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=data.yaml, degrees=0.0, deterministic=True, device=cpu, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=10, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=416, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=train20, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=D:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\runs\detect\train20, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=0, workspace=None
Overriding model.yaml nc=80 with nc=2

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    751702  ultralytics.nn.modules.head.Detect           [2, 16, None, [64, 128, 256]]
Model summary: 130 layers, 3,011,238 parameters, 3,011,222 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
train: Fast image access  (ping: 0.40.2 ms, read: 31.527.9 MB/s, size: 39.0 KB)
train: Scanning D:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\labels.cache... 4072 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 4072/4072 437.9Mit/s 0.0s
val: Fast image access  (ping: 0.30.1 ms, read: 60.612.4 MB/s, size: 42.1 KB)
val: Scanning D:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\valid\labels.cache... 122 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 122/122 12.8Mit/s 0.0s
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.001667, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Plotting labels to D:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\runs\detect\train20\labels.jpg...
Image sizes 416 train, 416 val
Using 0 dataloader workers
Logging results to D:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\runs\detect\train20
Starting training for 10 epochs...
Closing dataloader mosaic

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/10         0G     0.7524      1.225      1.146          9        416: 100% ━━━━━━━━━━━━ 1018/1018 1.3it/s 12:59<0.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 16/16 1.5it/s 10.8s0.7s
                   all        122        240      0.603      0.554      0.534      0.367

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/10         0G     0.7343     0.8332      1.122          5        416: 100% ━━━━━━━━━━━━ 1018/1018 1.6it/s 10:22<0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 16/16 3.4it/s 4.7s0.3s
                   all        122        240      0.569      0.755      0.724      0.526

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/10         0G     0.7031     0.6919      1.092          7        416: 100% ━━━━━━━━━━━━ 1018/1018 1.1it/s 14:55<1.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 16/16 1.5it/s 10.5s0.7s
                   all        122        240      0.684      0.731      0.758      0.563

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/10         0G      0.657     0.6075      1.068          8        416: 100% ━━━━━━━━━━━━ 1018/1018 1.0s/it 17:44<1.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 16/16 1.2it/s 13.2s0.9s
                   all        122        240      0.693      0.786      0.792      0.599

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/10         0G     0.6144     0.5398      1.041          4        416: 100% ━━━━━━━━━━━━ 1018/1018 1.0it/s 16:36<1.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 16/16 1.6it/s 10.3s0.7s
                   all        122        240      0.763      0.823      0.875      0.675

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/10         0G     0.5744     0.4787      1.014          5        416: 100% ━━━━━━━━━━━━ 1018/1018 1.0it/s 16:19<0.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 16/16 1.6it/s 10.2s0.7s
                   all        122        240       0.61      0.668      0.714      0.529

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/10         0G     0.5295     0.4329     0.9886          7        416: 100% ━━━━━━━━━━━━ 1018/1018 1.1it/s 15:38<0.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 16/16 1.6it/s 10.2s0.7s
                   all        122        240      0.693      0.738      0.789      0.613

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/10         0G     0.4878     0.3898     0.9713          6        416: 100% ━━━━━━━━━━━━ 1018/1018 4.2s/it 1:12:06<0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 16/16 3.4it/s 4.7s0.3s
                   all        122        240      0.489      0.782      0.708      0.547

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/10         0G     0.4622     0.3562     0.9542          6        416: 100% ━━━━━━━━━━━━ 1018/1018 2.3it/s 7:14<0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 16/16 3.3it/s 4.8s0.3s
                   all        122        240      0.585      0.801      0.762      0.612

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/10         0G     0.4356     0.3357     0.9387          7        416: 100% ━━━━━━━━━━━━ 1018/1018 2.4it/s 7:05<0.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 16/16 2.9it/s 5.5s0.4s
                   all        122        240      0.646       0.85        0.8      0.647

10 epochs completed in 3.208 hours.
Optimizer stripped from D:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\runs\detect\train20\weights\last.pt, 6.2MB
Optimizer stripped from D:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\runs\detect\train20\weights\best.pt, 6.2MB

Validating D:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\runs\detect\train20\weights\best.pt...
Ultralytics 8.4.15  Python-3.14.3 torch-2.10.0+cpu CPU (AMD Ryzen 7 7840HS w/ Radeon 780M Graphics)
Model summary (fused): 73 layers, 3,006,038 parameters, 0 gradients, 8.1 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 16/16 3.4it/s 4.7s0.3s
                   all        122        240       0.77      0.823      0.877      0.675
             authentic        110        184      0.753      0.913      0.916      0.717
           counterfeit         15         56      0.787      0.732      0.838      0.633
Speed: 0.6ms preprocess, 28.9ms inference, 0.0ms loss, 0.5ms postprocess per image
Results saved to D:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\runs\detect\train20

ultralytics.utils.metrics.DetMetrics object with attributes:

ap_class_index: array([0, 1])
box: ultralytics.utils.metrics.Metric object
confusion_matrix: <ultralytics.utils.metrics.ConfusionMatrix object at 0x0000024789A07F20>
curves: ['Precision-Recall(B)', 'F1-Confidence(B)', 'Precision-Confidence(B)', 'Recall-Confidence(B)']
curves_results: [[array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,
           0.33634,     0.33734,     0.33834,     0.33934,     0.34034,     0.34134,     0.34234,     0.34334,     0.34434,     0.34535,     0.34635,     0.34735,     0.34835,     0.34935,     0.35035,     0.35135,     0.35235,     0.35335,     0.35435,     0.35536,     0.35636,     0.35736,     0.35836,     0.35936,
           0.36036,     0.36136,     0.36236,     0.36336,     0.36436,     0.36537,     0.36637,     0.36737,     0.36837,     0.36937,     0.37037,     0.37137,     0.37237,     0.37337,     0.37437,     0.37538,     0.37638,     0.37738,     0.37838,     0.37938,     0.38038,     0.38138,     0.38238,     0.38338,
           0.38438,     0.38539,     0.38639,     0.38739,     0.38839,     0.38939,     0.39039,     0.39139,     0.39239,     0.39339,     0.39439,      0.3954,      0.3964,      0.3974,      0.3984,      0.3994,      0.4004,      0.4014,      0.4024,      0.4034,      0.4044,     0.40541,     0.40641,     0.40741,
           0.40841,     0.40941,     0.41041,     0.41141,     0.41241,     0.41341,     0.41441,     0.41542,     0.41642,     0.41742,     0.41842,     0.41942,     0.42042,     0.42142,     0.42242,     0.42342,     0.42442,     0.42543,     0.42643,     0.42743,     0.42843,     0.42943,     0.43043,     0.43143,
           0.43243,     0.43343,     0.43443,     0.43544,     0.43644,     0.43744,     0.43844,     0.43944,     0.44044,     0.44144,     0.44244,     0.44344,     0.44444,     0.44545,     0.44645,     0.44745,     0.44845,     0.44945,     0.45045,     0.45145,     0.45245,     0.45345,     0.45445,     0.45546,
           0.45646,     0.45746,     0.45846,     0.45946,     0.46046,     0.46146,     0.46246,     0.46346,     0.46446,     0.46547,     0.46647,     0.46747,     0.46847,     0.46947,     0.47047,     0.47147,     0.47247,     0.47347,     0.47447,     0.47548,     0.47648,     0.47748,     0.47848,     0.47948,
           0.48048,     0.48148,     0.48248,     0.48348,     0.48448,     0.48549,     0.48649,     0.48749,     0.48849,     0.48949,     0.49049,     0.49149,     0.49249,     0.49349,     0.49449,      0.4955,      0.4965,      0.4975,      0.4985,      0.4995,      0.5005,      0.5015,      0.5025,      0.5035,
            0.5045,     0.50551,     0.50651,     0.50751,     0.50851,     0.50951,     0.51051,     0.51151,     0.51251,     0.51351,     0.51451,     0.51552,     0.51652,     0.51752,     0.51852,     0.51952,     0.52052,     0.52152,     0.52252,     0.52352,     0.52452,     0.52553,     0.52653,     0.52753,
           0.52853,     0.52953,     0.53053,     0.53153,     0.53253,     0.53353,     0.53453,     0.53554,     0.53654,     0.53754,     0.53854,     0.53954,     0.54054,     0.54154,     0.54254,     0.54354,     0.54454,     0.54555,     0.54655,     0.54755,     0.54855,     0.54955,     0.55055,     0.55155,
           0.55255,     0.55355,     0.55455,     0.55556,     0.55656,     0.55756,     0.55856,     0.55956,     0.56056,     0.56156,     0.56256,     0.56356,     0.56456,     0.56557,     0.56657,     0.56757,     0.56857,     0.56957,     0.57057,     0.57157,     0.57257,     0.57357,     0.57457,     0.57558,
           0.57658,     0.57758,     0.57858,     0.57958,     0.58058,     0.58158,     0.58258,     0.58358,     0.58458,     0.58559,     0.58659,     0.58759,     0.58859,     0.58959,     0.59059,     0.59159,     0.59259,     0.59359,     0.59459,      0.5956,      0.5966,      0.5976,      0.5986,      0.5996,
            0.6006,      0.6016,      0.6026,      0.6036,      0.6046,     0.60561,     0.60661,     0.60761,     0.60861,     0.60961,     0.61061,     0.61161,     0.61261,     0.61361,     0.61461,     0.61562,     0.61662,     0.61762,     0.61862,     0.61962,     0.62062,     0.62162,     0.62262,     0.62362,
           0.62462,     0.62563,     0.62663,     0.62763,     0.62863,     0.62963,     0.63063,     0.63163,     0.63263,     0.63363,     0.63463,     0.63564,     0.63664,     0.63764,     0.63864,     0.63964,     0.64064,     0.64164,     0.64264,     0.64364,     0.64464,     0.64565,     0.64665,     0.64765,
           0.64865,     0.64965,     0.65065,     0.65165,     0.65265,     0.65365,     0.65465,     0.65566,     0.65666,     0.65766,     0.65866,     0.65966,     0.66066,     0.66166,     0.66266,     0.66366,     0.66466,     0.66567,     0.66667,     0.66767,     0.66867,     0.66967,     0.67067,     0.67167,
           0.67267,     0.67367,     0.67467,     0.67568,     0.67668,     0.67768,     0.67868,     0.67968,     0.68068,     0.68168,     0.68268,     0.68368,     0.68468,     0.68569,     0.68669,     0.68769,     0.68869,     0.68969,     0.69069,     0.69169,     0.69269,     0.69369,     0.69469,      0.6957,
            0.6967,      0.6977,      0.6987,      0.6997,      0.7007,      0.7017,      0.7027,      0.7037,      0.7047,     0.70571,     0.70671,     0.70771,     0.70871,     0.70971,     0.71071,     0.71171,     0.71271,     0.71371,     0.71471,     0.71572,     0.71672,     0.71772,     0.71872,     0.71972,
           0.72072,     0.72172,     0.72272,     0.72372,     0.72472,     0.72573,     0.72673,     0.72773,     0.72873,     0.72973,     0.73073,     0.73173,     0.73273,     0.73373,     0.73473,     0.73574,     0.73674,     0.73774,     0.73874,     0.73974,     0.74074,     0.74174,     0.74274,     0.74374,
           0.74474,     0.74575,     0.74675,     0.74775,     0.74875,     0.74975,     0.75075,     0.75175,     0.75275,     0.75375,     0.75475,     0.75576,     0.75676,     0.75776,     0.75876,     0.75976,     0.76076,     0.76176,     0.76276,     0.76376,     0.76476,     0.76577,     0.76677,     0.76777,
           0.76877,     0.76977,     0.77077,     0.77177,     0.77277,     0.77377,     0.77477,     0.77578,     0.77678,     0.77778,     0.77878,     0.77978,     0.78078,     0.78178,     0.78278,     0.78378,     0.78478,     0.78579,     0.78679,     0.78779,     0.78879,     0.78979,     0.79079,     0.79179,
           0.79279,     0.79379,     0.79479,      0.7958,      0.7968,      0.7978,      0.7988,      0.7998,      0.8008,      0.8018,      0.8028,      0.8038,      0.8048,     0.80581,     0.80681,     0.80781,     0.80881,     0.80981,     0.81081,     0.81181,     0.81281,     0.81381,     0.81481,     0.81582,
           0.81682,     0.81782,     0.81882,     0.81982,     0.82082,     0.82182,     0.82282,     0.82382,     0.82482,     0.82583,     0.82683,     0.82783,     0.82883,     0.82983,     0.83083,     0.83183,     0.83283,     0.83383,     0.83483,     0.83584,     0.83684,     0.83784,     0.83884,     0.83984,
           0.84084,     0.84184,     0.84284,     0.84384,     0.84484,     0.84585,     0.84685,     0.84785,     0.84885,     0.84985,     0.85085,     0.85185,     0.85285,     0.85385,     0.85485,     0.85586,     0.85686,     0.85786,     0.85886,     0.85986,     0.86086,     0.86186,     0.86286,     0.86386,
           0.86486,     0.86587,     0.86687,     0.86787,     0.86887,     0.86987,     0.87087,     0.87187,     0.87287,     0.87387,     0.87487,     0.87588,     0.87688,     0.87788,     0.87888,     0.87988,     0.88088,     0.88188,     0.88288,     0.88388,     0.88488,     0.88589,     0.88689,     0.88789,
           0.88889,     0.88989,     0.89089,     0.89189,     0.89289,     0.89389,     0.89489,      0.8959,      0.8969,      0.8979,      0.8989,      0.8999,      0.9009,      0.9019,      0.9029,      0.9039,      0.9049,     0.90591,     0.90691,     0.90791,     0.90891,     0.90991,     0.91091,     0.91191,
           0.91291,     0.91391,     0.91491,     0.91592,     0.91692,     0.91792,     0.91892,     0.91992,     0.92092,     0.92192,     0.92292,     0.92392,     0.92492,     0.92593,     0.92693,     0.92793,     0.92893,     0.92993,     0.93093,     0.93193,     0.93293,     0.93393,     0.93493,     0.93594,
           0.93694,     0.93794,     0.93894,     0.93994,     0.94094,     0.94194,     0.94294,     0.94394,     0.94494,     0.94595,     0.94695,     0.94795,     0.94895,     0.94995,     0.95095,     0.95195,     0.95295,     0.95395,     0.95495,     0.95596,     0.95696,     0.95796,     0.95896,     0.95996,
           0.96096,     0.96196,     0.96296,     0.96396,     0.96496,     0.96597,     0.96697,     0.96797,     0.96897,     0.96997,     0.97097,     0.97197,     0.97297,     0.97397,     0.97497,     0.97598,     0.97698,     0.97798,     0.97898,     0.97998,     0.98098,     0.98198,     0.98298,     0.98398,
           0.98498,     0.98599,     0.98699,     0.98799,     0.98899,     0.98999,     0.99099,     0.99199,     0.99299,     0.99399,     0.99499,       0.996,       0.997,       0.998,       0.999,           1]), array([[          1,           1,           1, ...,    0.011815,   0.0059075,           0],
       [          1,           1,           1, ...,   0.0044712,   0.0022356,           0]], shape=(2, 1000)), 'Recall', 'Precision'], [array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,
           0.33634,     0.33734,     0.33834,     0.33934,     0.34034,     0.34134,     0.34234,     0.34334,     0.34434,     0.34535,     0.34635,     0.34735,     0.34835,     0.34935,     0.35035,     0.35135,     0.35235,     0.35335,     0.35435,     0.35536,     0.35636,     0.35736,     0.35836,     0.35936,
           0.36036,     0.36136,     0.36236,     0.36336,     0.36436,     0.36537,     0.36637,     0.36737,     0.36837,     0.36937,     0.37037,     0.37137,     0.37237,     0.37337,     0.37437,     0.37538,     0.37638,     0.37738,     0.37838,     0.37938,     0.38038,     0.38138,     0.38238,     0.38338,
           0.38438,     0.38539,     0.38639,     0.38739,     0.38839,     0.38939,     0.39039,     0.39139,     0.39239,     0.39339,     0.39439,      0.3954,      0.3964,      0.3974,      0.3984,      0.3994,      0.4004,      0.4014,      0.4024,      0.4034,      0.4044,     0.40541,     0.40641,     0.40741,
           0.40841,     0.40941,     0.41041,     0.41141,     0.41241,     0.41341,     0.41441,     0.41542,     0.41642,     0.41742,     0.41842,     0.41942,     0.42042,     0.42142,     0.42242,     0.42342,     0.42442,     0.42543,     0.42643,     0.42743,     0.42843,     0.42943,     0.43043,     0.43143,
           0.43243,     0.43343,     0.43443,     0.43544,     0.43644,     0.43744,     0.43844,     0.43944,     0.44044,     0.44144,     0.44244,     0.44344,     0.44444,     0.44545,     0.44645,     0.44745,     0.44845,     0.44945,     0.45045,     0.45145,     0.45245,     0.45345,     0.45445,     0.45546,

In [4]:
import os
print(os.listdir("runs/detect/train"))

['args.yaml', 'labels.jpg', 'weights']

In [5]:
import os
print(os.listdir("runs/detect/train13/weights"))

['best.pt', 'last.pt']

In [6]:
model.val(data="data.yaml")

Ultralytics 8.4.15  Python-3.14.3 torch-2.10.0+cpu CPU (AMD Ryzen 7 7840HS w/ Radeon 780M Graphics)
Model summary (fused): 73 layers, 3,006,038 parameters, 0 gradients, 8.1 GFLOPs
val: Fast image access  (ping: 0.10.0 ms, read: 190.441.0 MB/s, size: 41.5 KB)
val: Scanning D:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\valid\labels.cache... 122 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 122/122 20.5Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 1.6it/s 4.9s0.7ss
                   all        122        240       0.77      0.823      0.877      0.675
             authentic        110        184      0.753      0.913      0.916      0.717
           counterfeit         15         56      0.787      0.732      0.838      0.633
Speed: 0.4ms preprocess, 29.7ms inference, 0.0ms loss, 0.5ms postprocess per image
Results saved to D:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\runs\detect\val6

ultralytics.utils.metrics.DetMetrics object with attributes:

ap_class_index: array([0, 1])
box: ultralytics.utils.metrics.Metric object
confusion_matrix: <ultralytics.utils.metrics.ConfusionMatrix object at 0x0000024784F3BA70>
curves: ['Precision-Recall(B)', 'F1-Confidence(B)', 'Precision-Confidence(B)', 'Recall-Confidence(B)']
curves_results: [[array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,
           0.33634,     0.33734,     0.33834,     0.33934,     0.34034,     0.34134,     0.34234,     0.34334,     0.34434,     0.34535,     0.34635,     0.34735,     0.34835,     0.34935,     0.35035,     0.35135,     0.35235,     0.35335,     0.35435,     0.35536,     0.35636,     0.35736,     0.35836,     0.35936,
           0.36036,     0.36136,     0.36236,     0.36336,     0.36436,     0.36537,     0.36637,     0.36737,     0.36837,     0.36937,     0.37037,     0.37137,     0.37237,     0.37337,     0.37437,     0.37538,     0.37638,     0.37738,     0.37838,     0.37938,     0.38038,     0.38138,     0.38238,     0.38338,
           0.38438,     0.38539,     0.38639,     0.38739,     0.38839,     0.38939,     0.39039,     0.39139,     0.39239,     0.39339,     0.39439,      0.3954,      0.3964,      0.3974,      0.3984,      0.3994,      0.4004,      0.4014,      0.4024,      0.4034,      0.4044,     0.40541,     0.40641,     0.40741,
           0.40841,     0.40941,     0.41041,     0.41141,     0.41241,     0.41341,     0.41441,     0.41542,     0.41642,     0.41742,     0.41842,     0.41942,     0.42042,     0.42142,     0.42242,     0.42342,     0.42442,     0.42543,     0.42643,     0.42743,     0.42843,     0.42943,     0.43043,     0.43143,
           0.43243,     0.43343,     0.43443,     0.43544,     0.43644,     0.43744,     0.43844,     0.43944,     0.44044,     0.44144,     0.44244,     0.44344,     0.44444,     0.44545,     0.44645,     0.44745,     0.44845,     0.44945,     0.45045,     0.45145,     0.45245,     0.45345,     0.45445,     0.45546,
           0.45646,     0.45746,     0.45846,     0.45946,     0.46046,     0.46146,     0.46246,     0.46346,     0.46446,     0.46547,     0.46647,     0.46747,     0.46847,     0.46947,     0.47047,     0.47147,     0.47247,     0.47347,     0.47447,     0.47548,     0.47648,     0.47748,     0.47848,     0.47948,
           0.48048,     0.48148,     0.48248,     0.48348,     0.48448,     0.48549,     0.48649,     0.48749,     0.48849,     0.48949,     0.49049,     0.49149,     0.49249,     0.49349,     0.49449,      0.4955,      0.4965,      0.4975,      0.4985,      0.4995,      0.5005,      0.5015,      0.5025,      0.5035,
            0.5045,     0.50551,     0.50651,     0.50751,     0.50851,     0.50951,     0.51051,     0.51151,     0.51251,     0.51351,     0.51451,     0.51552,     0.51652,     0.51752,     0.51852,     0.51952,     0.52052,     0.52152,     0.52252,     0.52352,     0.52452,     0.52553,     0.52653,     0.52753,
           0.52853,     0.52953,     0.53053,     0.53153,     0.53253,     0.53353,     0.53453,     0.53554,     0.53654,     0.53754,     0.53854,     0.53954,     0.54054,     0.54154,     0.54254,     0.54354,     0.54454,     0.54555,     0.54655,     0.54755,     0.54855,     0.54955,     0.55055,     0.55155,
           0.55255,     0.55355,     0.55455,     0.55556,     0.55656,     0.55756,     0.55856,     0.55956,     0.56056,     0.56156,     0.56256,     0.56356,     0.56456,     0.56557,     0.56657,     0.56757,     0.56857,     0.56957,     0.57057,     0.57157,     0.57257,     0.57357,     0.57457,     0.57558,
           0.57658,     0.57758,     0.57858,     0.57958,     0.58058,     0.58158,     0.58258,     0.58358,     0.58458,     0.58559,     0.58659,     0.58759,     0.58859,     0.58959,     0.59059,     0.59159,     0.59259,     0.59359,     0.59459,      0.5956,      0.5966,      0.5976,      0.5986,      0.5996,
            0.6006,      0.6016,      0.6026,      0.6036,      0.6046,     0.60561,     0.60661,     0.60761,     0.60861,     0.60961,     0.61061,     0.61161,     0.61261,     0.61361,     0.61461,     0.61562,     0.61662,     0.61762,     0.61862,     0.61962,     0.62062,     0.62162,     0.62262,     0.62362,
           0.62462,     0.62563,     0.62663,     0.62763,     0.62863,     0.62963,     0.63063,     0.63163,     0.63263,     0.63363,     0.63463,     0.63564,     0.63664,     0.63764,     0.63864,     0.63964,     0.64064,     0.64164,     0.64264,     0.64364,     0.64464,     0.64565,     0.64665,     0.64765,
           0.64865,     0.64965,     0.65065,     0.65165,     0.65265,     0.65365,     0.65465,     0.65566,     0.65666,     0.65766,     0.65866,     0.65966,     0.66066,     0.66166,     0.66266,     0.66366,     0.66466,     0.66567,     0.66667,     0.66767,     0.66867,     0.66967,     0.67067,     0.67167,
           0.67267,     0.67367,     0.67467,     0.67568,     0.67668,     0.67768,     0.67868,     0.67968,     0.68068,     0.68168,     0.68268,     0.68368,     0.68468,     0.68569,     0.68669,     0.68769,     0.68869,     0.68969,     0.69069,     0.69169,     0.69269,     0.69369,     0.69469,      0.6957,
            0.6967,      0.6977,      0.6987,      0.6997,      0.7007,      0.7017,      0.7027,      0.7037,      0.7047,     0.70571,     0.70671,     0.70771,     0.70871,     0.70971,     0.71071,     0.71171,     0.71271,     0.71371,     0.71471,     0.71572,     0.71672,     0.71772,     0.71872,     0.71972,
           0.72072,     0.72172,     0.72272,     0.72372,     0.72472,     0.72573,     0.72673,     0.72773,     0.72873,     0.72973,     0.73073,     0.73173,     0.73273,     0.73373,     0.73473,     0.73574,     0.73674,     0.73774,     0.73874,     0.73974,     0.74074,     0.74174,     0.74274,     0.74374,
           0.74474,     0.74575,     0.74675,     0.74775,     0.74875,     0.74975,     0.75075,     0.75175,     0.75275,     0.75375,     0.75475,     0.75576,     0.75676,     0.75776,     0.75876,     0.75976,     0.76076,     0.76176,     0.76276,     0.76376,     0.76476,     0.76577,     0.76677,     0.76777,
           0.76877,     0.76977,     0.77077,     0.77177,     0.77277,     0.77377,     0.77477,     0.77578,     0.77678,     0.77778,     0.77878,     0.77978,     0.78078,     0.78178,     0.78278,     0.78378,     0.78478,     0.78579,     0.78679,     0.78779,     0.78879,     0.78979,     0.79079,     0.79179,
           0.79279,     0.79379,     0.79479,      0.7958,      0.7968,      0.7978,      0.7988,      0.7998,      0.8008,      0.8018,      0.8028,      0.8038,      0.8048,     0.80581,     0.80681,     0.80781,     0.80881,     0.80981,     0.81081,     0.81181,     0.81281,     0.81381,     0.81481,     0.81582,
           0.81682,     0.81782,     0.81882,     0.81982,     0.82082,     0.82182,     0.82282,     0.82382,     0.82482,     0.82583,     0.82683,     0.82783,     0.82883,     0.82983,     0.83083,     0.83183,     0.83283,     0.83383,     0.83483,     0.83584,     0.83684,     0.83784,     0.83884,     0.83984,
           0.84084,     0.84184,     0.84284,     0.84384,     0.84484,     0.84585,     0.84685,     0.84785,     0.84885,     0.84985,     0.85085,     0.85185,     0.85285,     0.85385,     0.85485,     0.85586,     0.85686,     0.85786,     0.85886,     0.85986,     0.86086,     0.86186,     0.86286,     0.86386,
           0.86486,     0.86587,     0.86687,     0.86787,     0.86887,     0.86987,     0.87087,     0.87187,     0.87287,     0.87387,     0.87487,     0.87588,     0.87688,     0.87788,     0.87888,     0.87988,     0.88088,     0.88188,     0.88288,     0.88388,     0.88488,     0.88589,     0.88689,     0.88789,
           0.88889,     0.88989,     0.89089,     0.89189,     0.89289,     0.89389,     0.89489,      0.8959,      0.8969,      0.8979,      0.8989,      0.8999,      0.9009,      0.9019,      0.9029,      0.9039,      0.9049,     0.90591,     0.90691,     0.90791,     0.90891,     0.90991,     0.91091,     0.91191,
           0.91291,     0.91391,     0.91491,     0.91592,     0.91692,     0.91792,     0.91892,     0.91992,     0.92092,     0.92192,     0.92292,     0.92392,     0.92492,     0.92593,     0.92693,     0.92793,     0.92893,     0.92993,     0.93093,     0.93193,     0.93293,     0.93393,     0.93493,     0.93594,
           0.93694,     0.93794,     0.93894,     0.93994,     0.94094,     0.94194,     0.94294,     0.94394,     0.94494,     0.94595,     0.94695,     0.94795,     0.94895,     0.94995,     0.95095,     0.95195,     0.95295,     0.95395,     0.95495,     0.95596,     0.95696,     0.95796,     0.95896,     0.95996,
           0.96096,     0.96196,     0.96296,     0.96396,     0.96496,     0.96597,     0.96697,     0.96797,     0.96897,     0.96997,     0.97097,     0.97197,     0.97297,     0.97397,     0.97497,     0.97598,     0.97698,     0.97798,     0.97898,     0.97998,     0.98098,     0.98198,     0.98298,     0.98398,
           0.98498,     0.98599,     0.98699,     0.98799,     0.98899,     0.98999,     0.99099,     0.99199,     0.99299,     0.99399,     0.99499,       0.996,       0.997,       0.998,       0.999,           1]), array([[          1,           1,           1, ...,    0.011815,   0.0059075,           0],
       [          1,           1,           1, ...,   0.0044712,   0.0022356,           0]], shape=(2, 1000)), 'Recall', 'Precision'], [array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,
           0.33634,     0.33734,     0.33834,     0.33934,     0.34034,     0.34134,     0.34234,     0.34334,     0.34434,     0.34535,     0.34635,     0.34735,     0.34835,     0.34935,     0.35035,     0.35135,     0.35235,     0.35335,     0.35435,     0.35536,     0.35636,     0.35736,     0.35836,     0.35936,
           0.36036,     0.36136,     0.36236,     0.36336,     0.36436,     0.36537,     0.36637,     0.36737,     0.36837,     0.36937,     0.37037,     0.37137,     0.37237,     0.37337,     0.37437,     0.37538,     0.37638,     0.37738,     0.37838,     0.37938,     0.38038,     0.38138,     0.38238,     0.38338,
           0.38438,     0.38539,     0.38639,     0.38739,     0.38839,     0.38939,     0.39039,     0.39139,     0.39239,     0.39339,     0.39439,      0.3954,      0.3964,      0.3974,      0.3984,      0.3994,      0.4004,      0.4014,      0.4024,      0.4034,      0.4044,     0.40541,     0.40641,     0.40741,
           0.40841,     0.40941,     0.41041,     0.41141,     0.41241,     0.41341,     0.41441,     0.41542,     0.41642,     0.41742,     0.41842,     0.41942,     0.42042,     0.42142,     0.42242,     0.42342,     0.42442,     0.42543,     0.42643,     0.42743,     0.42843,     0.42943,     0.43043,     0.43143,
           0.43243,     0.43343,     0.43443,     0.43544,     0.43644,     0.43744,     0.43844,     0.43944,     0.44044,     0.44144,     0.44244,     0.44344,     0.44444,     0.44545,     0.44645,     0.44745,     0.44845,     0.44945,     0.45045,     0.45145,     0.45245,     0.45345,     0.45445,     0.45546,

In [9]:
from ultralytics import YOLO
import os

model = YOLO("runs/detect/train13/weights/best.pt")

# TRAIN
model.predict(
    source="train/images",
    save_crop=True,
    name="crops_train",
    conf=0.25
)

# VALID
model.predict(
    source="valid/images",
    save_crop=True,
    name="crops_valid",
    conf=0.25
)

# TEST
model.predict(
    source="test/images",
    save_crop=True,
    name="crops_test",
    conf=0.25
)

WARNING
Inference results will accumulate in RAM unless `stream=True` is passed, which can cause out-of-memory errors for large
sources or long-running streams and videos. See https://docs.ultralytics.com/modes/predict/ for help.

Example:
    results = model(source=..., stream=True)  # generator of Results objects
    for r in results:
        boxes = r.boxes  # Boxes object for bbox outputs
        masks = r.masks  # Masks object for segment masks outputs
        probs = r.probs  # Class probabilities for classification outputs

image 1/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\109118801_3244498252272873_7164080379624931851_n_jpg.rf.272e6f3e15ce8f684d33af1920ff3617.jpg: 416x416 6 counterfeits, 36.9ms
image 2/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\109118801_3244498252272873_7164080379624931851_n_jpg.rf.c5cdf4a1b46a0ed4f982d80eadd2fc2d.jpg: 416x416 1 authentic, 5 counterfeits, 35.6ms
image 3/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\109118801_3244498252272873_7164080379624931851_n_jpg.rf.ff9ade4730d4dfdf3bf8a3a3c8ab45b5.jpg: 416x416 4 counterfeits, 34.2ms
image 4/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\109573147_3244498132272885_6335025209478035818_n_jpg.rf.19eef16df28e2f1c4a03a6f6b0ca9802.jpg: 416x416 7 counterfeits, 34.8ms
image 5/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\109573147_3244498132272885_6335025209478035818_n_jpg.rf.428a22df7804752c990cccdd03d7b685.jpg: 416x416 9 counterfeits, 40.6ms
image 6/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\109573147_3244498132272885_6335025209478035818_n_jpg.rf.caa69d31f0d94a41736f2c81a06c8445.jpg: 416x416 9 counterfeits, 34.4ms
image 7/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\109956533_3244497725606259_3458066695358260920_n_jpg.rf.a71bd9782d5d1ac7bd7daeb108bad400.jpg: 416x416 1 authentic, 6 counterfeits, 37.2ms
image 8/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\109956533_3244497725606259_3458066695358260920_n_jpg.rf.ab0c261de296b3718394e9f2de2320a9.jpg: 416x416 4 counterfeits, 35.2ms
image 9/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\109956533_3244497725606259_3458066695358260920_n_jpg.rf.f9f373b37b350449cd3fb74d496e9ec1.jpg: 416x416 4 counterfeits, 35.9ms
image 10/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\110080868_3244497848939580_2970928293483393329_n_jpg.rf.1719824a4c3614a270e4fd48f88a62f6.jpg: 416x416 6 counterfeits, 39.2ms
image 11/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\110080868_3244497848939580_2970928293483393329_n_jpg.rf.43fedec350562a573405b04673a56020.jpg: 416x416 1 authentic, 6 counterfeits, 40.9ms
image 12/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\110080868_3244497848939580_2970928293483393329_n_jpg.rf.b5bcf2237d0bb6bb400c235d2fb3db72.jpg: 416x416 1 authentic, 6 counterfeits, 51.2ms
image 13/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\110087553_3244497862272912_6330145168259268761_n_jpg.rf.0f9992b118a565a79c600a08a76efd6c.jpg: 416x416 6 counterfeits, 36.4ms
image 14/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\110087553_3244497862272912_6330145168259268761_n_jpg.rf.5d9744ae7bac84a14fec5711f120ade4.jpg: 416x416 1 authentic, 5 counterfeits, 34.0ms
image 15/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\110087553_3244497862272912_6330145168259268761_n_jpg.rf.9fc235cae462f4158f4950dc2d4cd17b.jpg: 416x416 1 authentic, 5 counterfeits, 33.4ms
image 16/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\110128855_3244497018939663_8398222400786658473_n_jpg.rf.1d9a7749ae7bfc763d0cc507fd464654.jpg: 416x416 2 authentics, 4 counterfeits, 36.7ms
image 17/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\110128855_3244497018939663_8398222400786658473_n_jpg.rf.20e3ccd2750e74dab00d34887fa56769.jpg: 416x416 7 counterfeits, 37.9ms
image 18/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\110128855_3244497018939663_8398222400786658473_n_jpg.rf.77bb645229383b8073b6842bc93cb997.jpg: 416x416 1 authentic, 6 counterfeits, 76.0ms
image 19/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\110334045_3244498002272898_7054935609460571205_n_jpg.rf.1c3a0425cb1436da01d954c7f50e8096.jpg: 416x416 7 counterfeits, 37.0ms
image 20/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\110334045_3244498002272898_7054935609460571205_n_jpg.rf.8475b4b9bad7abce6cf566d1d1a29984.jpg: 416x416 9 counterfeits, 37.2ms
image 21/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\110334045_3244498002272898_7054935609460571205_n_jpg.rf.c3120d39c49ee32937501d0f357b5bad.jpg: 416x416 6 counterfeits, 37.0ms
image 22/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\110657861_3244497582272940_2325276206631652556_n_jpg.rf.5e958c2e4e7cd814620f96505fb91718.jpg: 416x416 7 counterfeits, 33.9ms
image 23/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\110657861_3244497582272940_2325276206631652556_n_jpg.rf.adb34fb2574c779275583ec27759734e.jpg: 416x416 7 counterfeits, 37.2ms
image 24/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\110657861_3244497582272940_2325276206631652556_n_jpg.rf.f843c9e7eb421892900edc28961f3c28.jpg: 416x416 7 counterfeits, 33.7ms
image 25/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\138757378_3748083985247628_373855157767140341_n_png.rf.1f3cb9e926c16feb7873f1989247c6fe.jpg: 416x416 6 counterfeits, 37.6ms
image 26/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\138757378_3748083985247628_373855157767140341_n_png.rf.5fc222cf614ecbc73c25b70726490e51.jpg: 416x416 5 counterfeits, 41.5ms
image 27/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\138757378_3748083985247628_373855157767140341_n_png.rf.f187c57bd2fb94ca879c0365b148abf2.jpg: 416x416 7 counterfeits, 36.2ms
image 28/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\1434-2020_png.rf.1e88440a09b650f8c6ebdf6558f01268.jpg: 416x416 10 counterfeits, 34.7ms
image 29/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\1434-2020_png.rf.a0ec63d49fb9d801fc14d36706a1af4a.jpg: 416x416 10 counterfeits, 33.5ms
image 30/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\1434-2020_png.rf.d23fd003882131dccdccb32dbdd75714.jpg: 416x416 10 counterfeits, 35.3ms
image 31/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\1877_png.rf.141a49282804e6684f6477aa507a49a8.jpg: 416x416 1 authentic, 4 counterfeits, 35.8ms
image 32/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\1877_png.rf.42fd102e5a30779ee121d9408cfcdbaf.jpg: 416x416 9 counterfeits, 35.7ms
image 33/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\1877_png.rf.f8381f327add820faf9ce4bc437d483b.jpg: 416x416 6 counterfeits, 35.5ms
image 34/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\190360375_4121964301192926_5836747406893149139_n_jpg.rf.981448aaf8b1e21cc6226a7ae218fd48.jpg: 416x416 10 counterfeits, 36.3ms
image 35/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\190360375_4121964301192926_5836747406893149139_n_jpg.rf.cd6d0f7ab64eeb3d331bff26e1cf2c87.jpg: 416x416 9 counterfeits, 34.8ms
image 36/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\190360375_4121964301192926_5836747406893149139_n_jpg.rf.e7b60fbfe3a5e0e513b956db9b78dafb.jpg: 416x416 1 authentic, 11 counterfeits, 33.4ms
image 37/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\190794092_4121936044529085_8971199346508043266_n_jpg.rf.59dc6dbb1e899c02de84acab50460f0f.jpg: 416x416 1 authentic, 14 counterfeits, 37.5ms
image 38/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\190794092_4121936044529085_8971199346508043266_n_jpg.rf.7fd40c667a4c5029157114582118051c.jpg: 416x416 9 counterfeits, 33.6ms
image 39/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\190794092_4121936044529085_8971199346508043266_n_jpg.rf.90c9ad93ff0b3b626b2f0c26b9a8e3b3.jpg: 416x416 11 counterfeits, 33.9ms
image 40/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\191764997_4121888921200464_8342069514000311514_n_jpg.rf.106593ec9a076e83548680ccbc390b44.jpg: 416x416 9 counterfeits, 72.5ms
image 41/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\191764997_4121888921200464_8342069514000311514_n_jpg.rf.132b76e66b1286166f109dc26e551abc.jpg: 416x416 1 authentic, 9 counterfeits, 80.0ms
image 42/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\191764997_4121888921200464_8342069514000311514_n_jpg.rf.b1752cafb2c834bdb2fac64f0e65c27d.jpg: 416x416 8 counterfeits, 73.8ms
image 43/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\2020-1348_10-1-_jpg.rf.61ef91f2704150557d59128334806b09.jpg: 416x416 2 counterfeits, 80.8ms
image 44/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\2020-1348_10-1-_jpg.rf.c0b8c3e35378146ea389987cb00fdf13.jpg: 416x416 2 counterfeits, 72.0ms
image 45/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\2020-1348_10-1-_jpg.rf.fed2e744d89ef09575f882c089e3784e.jpg: 416x416 2 counterfeits, 75.0ms
image 46/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\2020-1348_14_jpg.rf.9e2ba611c8ef580e38b4ce3a755e081a.jpg: 416x416 2 counterfeits, 77.4ms
image 47/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\2020-1348_14_jpg.rf.d5aeef78e7ba6fa8113f97a930f684e0.jpg: 416x416 1 authentic, 2 counterfeits, 76.1ms
image 48/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\2020-1348_14_jpg.rf.f43b18935209ae8423c4768de2314a14.jpg: 416x416 2 authentics, 2 counterfeits, 79.4ms
image 49/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\2020-1348_16_jpg.rf.0b03734fde55866bd7eb3aca328ee379.jpg: 416x416 2 counterfeits, 71.1ms
image 50/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\2020-1348_16_jpg.rf.ddf30aa4ccf7e7f98b5331ba49049c1e.jpg: 416x416 2 counterfeits, 71.3ms
image 51/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\2020-1348_16_jpg.rf.fe154fcf43a5ece203d01fe48ab1c91b.jpg: 416x416 2 counterfeits, 74.3ms
image 52/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\2020-1348_18_jpg.rf.48fec52816e895df84c54f475844f4d4.jpg: 416x416 4 counterfeits, 79.6ms
image 53/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\2020-1348_18_jpg.rf.b9749ccca5930267f5a319dc4e0e9bd6.jpg: 416x416 2 counterfeits, 74.1ms
image 54/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\2020-1348_18_jpg.rf.e91892966ad1cf8062e586c70c2ee089.jpg: 416x416 2 counterfeits, 74.0ms
image 55/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\2020-1348_2-1-_jpg.rf.c627c1d74bd6ea2f16dd5fb6715d22f7.jpg: 416x416 2 counterfeits, 74.3ms
image 56/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\2020-1348_2-1-_jpg.rf.d5169e13584a158f9ada5b27e39b7baa.jpg: 416x416 4 counterfeits, 73.9ms
image 57/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\2020-1348_2-1-_jpg.rf.fde81dc641d4d20267d8908717be937c.jpg: 416x416 2 counterfeits, 103.6ms
image 58/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\2020-1348_23_jpg.rf.6925d69fe7915fa135e25832c569afa8.jpg: 416x416 2 authentics, 2 counterfeits, 76.9ms
image 59/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\2020-1348_23_jpg.rf.adc5d63b530f61f5621086931d5c5b88.jpg: 416x416 1 authentic, 2 counterfeits, 75.4ms
image 60/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\2020-1348_23_jpg.rf.b51efb82d98a450d2c375669cf623ac1.jpg: 416x416 2 authentics, 2 counterfeits, 49.2ms
image 61/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\2020-1348_24_jpg.rf.6cbdce2fc8e03b0b6c55af349cdd73e7.jpg: 416x416 1 counterfeit, 35.8ms
image 62/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\2020-1348_24_jpg.rf.793ff51f047735c6582067b83452f941.jpg: 416x416 2 counterfeits, 32.9ms
image 63/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\2020-1348_24_jpg.rf.b9feec1f68f85b83aeba4c6aa42fe931.jpg: 416x416 1 authentic, 1 counterfeit, 38.8ms
image 64/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\2020-1348_29-1-_jpg.rf.2222004ad0ba448d7a4cffc15f576b38.jpg: 416x416 2 authentics, 1 counterfeit, 32.9ms
image 65/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\2020-1348_29-1-_jpg.rf.9073c452eb726c65df14c797a717f985.jpg: 416x416 2 counterfeits, 42.7ms
image 66/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\2020-1348_29-1-_jpg.rf.df6267cec11f6b28f36223781331f3a3.jpg: 416x416 2 counterfeits, 36.9ms
image 67/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\2020-1348_31_jpg.rf.043495094204bc3efd539225ee63cdcd.jpg: 416x416 1 authentic, 4 counterfeits, 36.3ms
image 68/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\2020-1348_31_jpg.rf.557cbf90fd3e4c86a42ca21a31fe53c3.jpg: 416x416 2 authentics, 3 counterfeits, 47.2ms
image 69/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\2020-1348_31_jpg.rf.77fbbafc5ed6cf0c1bffaea44423355f.jpg: 416x416 5 counterfeits, 50.7ms
image 70/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\2020-1348_33-1-_jpg.rf.2896543e87eb550300a93dcf41f188ac.jpg: 416x416 3 counterfeits, 54.9ms
image 71/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\2020-1348_33-1-_jpg.rf.a4d36fa10b3571a72a577caedcf65542.jpg: 416x416 7 counterfeits, 47.1ms
image 72/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\2020-1348_33-1-_jpg.rf.bcbf6bddb127ec918453abf3b31e463c.jpg: 416x416 4 counterfeits, 33.3ms
image 73/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\2020-1348_5_jpg.rf.0c466f7f607dafd5d59317a424c3a24f.jpg: 416x416 2 authentics, 36.1ms
image 74/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\2020-1348_5_jpg.rf.2de8a6a160157176610709ae4b6ed63b.jpg: 416x416 1 authentic, 2 counterfeits, 34.6ms
image 75/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\2020-1348_5_jpg.rf.7027c16d99ddb90c60224427e532c06e.jpg: 416x416 2 authentics, 35.8ms
image 76/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\Authentic-vs-fake-Medicol-Advance-2048x1150_jpg.rf.16ecb5f1dddb547e6e6547ebce7f2e48.jpg: 416x416 11 counterfeits, 33.7ms
image 77/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\Authentic-vs-fake-Medicol-Advance-2048x1150_jpg.rf.7377748015f43b912ecfc297f5d91784.jpg: 416x416 11 counterfeits, 34.0ms
image 78/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\Authentic-vs-fake-Medicol-Advance-2048x1150_jpg.rf.8b481afcbadfcfff10a84f061f7db88b.jpg: 416x416 4 counterfeits, 35.0ms
image 79/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\FAKENEOZEP-AA_jpg.rf.1730a191acd1e662545fb863ff75556a.jpg: 416x416 4 counterfeits, 36.9ms
image 80/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\FAKENEOZEP-AA_jpg.rf.1efcd8c655fd0c5acc43191a8388c9c4.jpg: 416x416 1 authentic, 4 counterfeits, 33.8ms
image 81/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\FAKENEOZEP-AA_jpg.rf.8c5c808905511f0dd836caeaffa7cde3.jpg: 416x416 4 counterfeits, 33.6ms
image 82/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\FDA-Advisory-No-2020-1348_jpg.rf.1925b06a2335fe155da0d975d8300bf4.jpg: 416x416 5 counterfeits, 35.9ms
image 83/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\FDA-Advisory-No-2020-1348_jpg.rf.cd9e0bf5463a742f21ea70fe3e459cc7.jpg: 416x416 1 authentic, 4 counterfeits, 33.4ms
image 84/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\FDA-Advisory-No-2020-1348_jpg.rf.d8f6fbbd1ae482f14c2272ed591085eb.jpg: 416x416 1 authentic, 4 counterfeits, 35.1ms
image 85/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\FDA-Advisory-No-2020-2177_png.rf.2d34c84e6e8ee128374b7e249cdd54cf.jpg: 416x416 5 counterfeits, 32.7ms
image 86/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\FDA-Advisory-No-2020-2177_png.rf.53faaab659eed75096c3e102b95f1770.jpg: 416x416 5 counterfeits, 36.5ms
image 87/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\FDA-Advisory-No-2020-2177_png.rf.d464ea87a365e7166544f7f3b1fdc0cd.jpg: 416x416 2 authentics, 5 counterfeits, 34.2ms
image 88/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\FDA-Advisory-No-2021-0139_png.rf.1c28aa012dcaf040c66dbf3a1efb2441.jpg: 416x416 7 counterfeits, 36.1ms
image 89/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\FDA-Advisory-No-2021-0139_png.rf.b5ea4ce129fe2f366c342becb1ffedab.jpg: 416x416 7 counterfeits, 33.8ms
image 90/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\FDA-Advisory-No-2021-0139_png.rf.f0e36168d164564b8e246d25bb0fc3aa.jpg: 416x416 7 counterfeits, 35.5ms
image 91/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\FDA-Advisory-No-2021-0363-1_png.rf.8a7e6c99032a04cb268e1c0519cdaabe.jpg: 416x416 9 counterfeits, 34.5ms
image 92/4072 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\train\images\FDA-Advisory-No-2021-0363-1_png.rf.9f05e5ed98cb90503c71f5ac8986cdc2.jpg: 416x416 1 authentic, 8 counterfeits, 34.6ms

[ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'authentic', 1: 'counterfeit'}
 obb: None
 orig_img: array([[[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        ...,

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]]], shape=(640, 640, 3), dtype=uint8)
 orig_shape: (640, 640)
 path: 'd:\\research papers\\jenil_sir_project\\Counterfeit_med_detection.v4i.yolov8\\test\\images\\110131889_3244497975606234_3802007184609585998_n_jpg.rf.fa1c6e5bb081aea29651809722b6a8d0.jpg'
 probs: None
 save_dir: 'D:\\research papers\\jenil_sir_project\\Counterfeit_med_detection.v4i.yolov8\\runs\\detect\\crops_test'
 speed: {'preprocess': 1.5536999562755227, 'inference': 33.36620004847646, 'postprocess': 0.9801998967304826},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'authentic', 1: 'counterfeit'}
 obb: None
 orig_img: array([[[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        ...,

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]]], shape=(640, 640, 3), dtype=uint8)
 orig_shape: (640, 640)
 path: 'd:\\research papers\\jenil_sir_project\\Counterfeit_med_detection.v4i.yolov8\\test\\images\\110717660_3244498335606198_2694477071745798285_n_jpg.rf.2003d583bf4f7e611decd258c28b9498.jpg'
 probs: None
 save_dir: 'D:\\research papers\\jenil_sir_project\\Counterfeit_med_detection.v4i.yolov8\\runs\\detect\\crops_test'
 speed: {'preprocess': 2.3892000317573547, 'inference': 37.66859997995198, 'postprocess': 0.7749999640509486},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'authentic', 1: 'counterfeit'}
 obb: None
 orig_img: array([[[ 19,  38, 255],
         [ 19,  38, 255],
         [ 19,  38, 255],
         ...,
         [ 19,  40, 252],
         [ 19,  40, 252],
         [ 19,  40, 252]],

        [[ 19,  38, 255],
         [ 19,  38, 255],
         [ 19,  38, 255],
         ...,
         [ 19,  40, 252],
         [ 19,  40, 252],
         [ 19,  40, 252]],

        [[ 19,  38, 255],
         [ 19,  38, 255],
         [ 19,  38, 255],
         ...,
         [ 19,  40, 252],
         [ 19,  40, 252],
         [ 19,  40, 252]],

        ...,

        [[255, 249, 255],
         [255, 250, 255],
         [255, 251, 255],
         ...,
         [255, 254, 250],
         [255, 255, 249],
         [255, 255, 249]],

        [[255, 249, 255],
         [255, 251, 255],
         [255, 252, 255],
         ...,
         [255, 254, 250],
         [255, 255, 249],
         [255, 255, 249]],

        [[255, 249, 255],
         [255, 251, 255],
         [255, 252, 255],
         ...,
         [255, 254, 250],
         [255, 255, 249],
         [255, 255, 249]]], shape=(640, 640, 3), dtype=uint8)
 orig_shape: (640, 640)
 path: 'd:\\research papers\\jenil_sir_project\\Counterfeit_med_detection.v4i.yolov8\\test\\images\\158964877_3907723632616995_1725415267995819979_n_jpg.rf.8a87c0a44aeb15610008171fcb852964.jpg'
 probs: None
 save_dir: 'D:\\research papers\\jenil_sir_project\\Counterfeit_med_detection.v4i.yolov8\\runs\\detect\\crops_test'
 speed: {'preprocess': 2.7995998971164227, 'inference': 34.82790000271052, 'postprocess': 0.6822000723332167},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'authentic', 1: 'counterfeit'}
 obb: None
 orig_img: array([[[ 17,  38, 253],
         [ 17,  38, 253],
         [ 17,  38, 253],
         ...,
         [ 18,  39, 254],
         [ 16,  37, 252],
         [ 14,  35, 250]],

        [[ 17,  38, 253],
         [ 17,  38, 253],
         [ 17,  38, 253],
         ...,
         [ 18,  39, 254],
         [ 16,  37, 252],
         [ 14,  35, 250]],

        [[ 17,  38, 253],
         [ 17,  38, 253],
         [ 17,  38, 253],
         ...,
         [ 18,  39, 254],
         [ 16,  37, 252],
         [ 14,  35, 250]],

        ...,

        [[254, 254, 254],
         [254, 254, 254],
         [254, 254, 254],
         ...,
         [254, 254, 254],
         [254, 254, 254],
         [254, 254, 254]],

        [[254, 254, 254],
         [254, 254, 254],
         [254, 254, 254],
         ...,
         [254, 254, 254],
         [254, 254, 254],
         [254, 254, 254]],

        [[254, 254, 254],
         [254, 254, 254],
         [254, 254, 254],
         ...,
         [254, 254, 254],
         [254, 254, 254],
         [254, 254, 254]]], shape=(640, 640, 3), dtype=uint8)
 orig_shape: (640, 640)
 path: 'd:\\research papers\\jenil_sir_project\\Counterfeit_med_detection.v4i.yolov8\\test\\images\\191489945_4122074827848540_4141220302232318049_n_jpg.rf.b72edfea0236850b0baab874268c29e0.jpg'
 probs: None
 save_dir: 'D:\\research papers\\jenil_sir_project\\Counterfeit_med_detection.v4i.yolov8\\runs\\detect\\crops_test'
 speed: {'preprocess': 2.256499952636659, 'inference': 35.62079998664558, 'postprocess': 0.7719999412074685},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'authentic', 1: 'counterfeit'}
 obb: None
 orig_img: array([[[255, 255, 255],
         [244, 244, 244],
         [231, 231, 231],
         ...,
         [255, 255, 255],
         [253, 253, 253],
         [249, 249, 249]],

        [[250, 250, 250],
         [244, 244, 244],
         [224, 224, 224],
         ...,
         [248, 248, 248],
         [249, 249, 249],
         [248, 248, 248]],

        [[242, 242, 242],
         [247, 247, 247],
         [224, 224, 224],
         ...,
         [254, 254, 254],
         [255, 255, 255],
         [255, 255, 255]],

        ...,

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [252, 252, 252]],

        [[255, 255, 255],
         [255, 255, 255],
         [251, 251, 251],
         ...,
         [253, 253, 253],
         [253, 253, 253],
         [253, 253, 253]],

        [[255, 255, 255],
         [251, 251, 251],
         [249, 249, 249],
         ...,
         [255, 255, 255],
         [252, 252, 252],
         [255, 255, 255]]], shape=(640, 640, 3), dtype=uint8)
 orig_shape: (640, 640)
 path: 'd:\\research papers\\jenil_sir_project\\Counterfeit_med_detection.v4i.yolov8\\test\\images\\2020-1348_22_jpg.rf.196df5521cbcb231746e0af011ee389d.jpg'
 probs: None
 save_dir: 'D:\\research papers\\jenil_sir_project\\Counterfeit_med_detection.v4i.yolov8\\runs\\detect\\crops_test'
 speed: {'preprocess': 1.6687000170350075, 'inference': 47.98649996519089, 'postprocess': 0.6415999960154295},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'authentic', 1: 'counterfeit'}
 obb: None
 orig_img: array([[[254, 254, 254],
         [254, 254, 254],
         [254, 254, 254],
         ...,
         [254, 254, 254],
         [254, 254, 254],
         [254, 254, 254]],

        [[254, 254, 254],
         [254, 254, 254],
         [254, 254, 254],
         ...,
         [254, 254, 254],
         [254, 254, 254],
         [254, 254, 254]],

        [[254, 254, 254],
         [254, 254, 254],
         [254, 254, 254],
         ...,
         [254, 254, 254],
         [254, 254, 254],
         [254, 254, 254]],

        ...,

        [[255, 255, 255],
         [254, 254, 254],
         [253, 253, 253],
         ...,
         [254, 254, 254],
         [254, 254, 254],
         [254, 254, 254]],

        [[251, 251, 251],
         [251, 251, 251],
         [251, 251, 251],
         ...,
         [254, 254, 254],
         [254, 254, 254],
         [254, 254, 254]],

        [[247, 247, 247],
         [248, 248, 248],
         [249, 249, 249],
         ...,
         [254, 254, 254],
         [254, 254, 254],
         [254, 254, 254]]], shape=(640, 640, 3), dtype=uint8)
 orig_shape: (640, 640)
 path: 'd:\\research papers\\jenil_sir_project\\Counterfeit_med_detection.v4i.yolov8\\test\\images\\FDA-Advisory-No-2022-0611-15_png.rf.50af905076c1c051743d93d2f67a0795.jpg'
 probs: None
 save_dir: 'D:\\research papers\\jenil_sir_project\\Counterfeit_med_detection.v4i.yolov8\\runs\\detect\\crops_test'
 speed: {'preprocess': 1.489899936132133, 'inference': 33.422600012272596, 'postprocess': 0.798200024291873},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'authentic', 1: 'counterfeit'}
 obb: None
 orig_img: array([[[254, 254, 254],
         [254, 254, 254],
         [254, 254, 254],
         ...,
         [254, 254, 254],
         [254, 254, 254],
         [254, 254, 254]],

        [[254, 254, 254],
         [254, 254, 254],
         [254, 254, 254],
         ...,
         [254, 254, 254],
         [254, 254, 254],
         [254, 254, 254]],

        [[254, 254, 254],
         [254, 254, 254],
         [254, 254, 254],
         ...,
         [254, 254, 254],
         [254, 254, 254],
         [254, 254, 254]],

        ...,

        [[255, 255, 255],
         [254, 254, 254],
         [253, 253, 253],
         ...,
         [254, 254, 254],
         [254, 254, 254],
         [254, 254, 254]],

        [[251, 251, 251],
         [251, 251, 251],
         [251, 251, 251],
         ...,
         [254, 254, 254],
         [254, 254, 254],
         [254, 254, 254]],

        [[247, 247, 247],
         [248, 248, 248],
         [249, 249, 249],
         ...,
         [254, 254, 254],
         [254, 254, 254],
         [254, 254, 254]]], shape=(640, 640, 3), dtype=uint8)
 orig_shape: (640, 640)
 path: 'd:\\research papers\\jenil_sir_project\\Counterfeit_med_detection.v4i.yolov8\\test\\images\\FDA-Advisory-No-2022-0611-19_png.rf.c8a50386b1bb7b64b6ee92126eb3dabf.jpg'
 probs: None
 save_dir: 'D:\\research papers\\jenil_sir_project\\Counterfeit_med_detection.v4i.yolov8\\runs\\detect\\crops_test'
 speed: {'preprocess': 1.1770999990403652, 'inference': 32.22189994994551, 'postprocess': 0.7475999882444739},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'authentic', 1: 'counterfeit'}
 obb: None
 orig_img: array([[[254, 254, 254],
         [254, 254, 254],
         [254, 254, 254],
         ...,
         [254, 254, 254],
         [254, 254, 254],
         [254, 254, 254]],

        [[254, 254, 254],
         [254, 254, 254],
         [254, 254, 254],
         ...,
         [254, 254, 254],
         [254, 254, 254],
         [254, 254, 254]],

        [[254, 254, 254],
         [254, 254, 254],
         [254, 254, 254],
         ...,
         [254, 254, 254],
         [254, 254, 254],
         [254, 254, 254]],

        ...,

        [[255, 255, 255],
         [254, 254, 254],
         [253, 253, 253],
         ...,
         [254, 254, 254],
         [254, 254, 254],
         [254, 254, 254]],

        [[251, 251, 251],
         [251, 251, 251],
         [251, 251, 251],
         ...,
         [254, 254, 254],
         [254, 254, 254],
         [254, 254, 254]],

        [[247, 247, 247],
         [248, 248, 248],
         [249, 249, 249],
         ...,
         [254, 254, 254],
         [254, 254, 254],
         [254, 254, 254]]], shape=(640, 640, 3), dtype=uint8)
 orig_shape: (640, 640)
 path: 'd:\\research papers\\jenil_sir_project\\Counterfeit_med_detection.v4i.yolov8\\test\\images\\FDA-Advisory-No-2022-0611-22_png.rf.5c8e2af047b4e5f36f3cf868d9f45322.jpg'
 probs: None
 save_dir: 'D:\\research papers\\jenil_sir_project\\Counterfeit_med_detection.v4i.yolov8\\runs\\detect\\crops_test'
 speed: {'preprocess': 2.3831999860703945, 'inference': 36.65480006020516, 'postprocess': 0.775099964812398},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'authentic', 1: 'counterfeit'}
 obb: None
 orig_img: array([[[254, 254, 254],
         [254, 254, 254],
         [254, 254, 254],
         ...,
         [254, 254, 254],
         [254, 254, 254],
         [254, 254, 254]],

        [[254, 254, 254],
         [254, 254, 254],
         [254, 254, 254],
         ...,
         [254, 254, 254],
         [254, 254, 254],
         [254, 254, 254]],

        [[254, 254, 254],
         [254, 254, 254],
         [254, 254, 254],
         ...,
         [254, 254, 254],
         [254, 254, 254],
         [254, 254, 254]],

        ...,

        [[255, 255, 255],
         [254, 254, 254],
         [253, 253, 253],
         ...,
         [254, 254, 254],
         [254, 254, 254],
         [254, 254, 254]],

        [[251, 251, 251],
         [251, 251, 251],
         [251, 251, 251],
         ...,
         [254, 254, 254],
         [254, 254, 254],
         [254, 254, 254]],

        [[247, 247, 247],
         [248, 248, 248],
         [249, 249, 249],
         ...,
         [254, 254, 254],
         [254, 254, 254],
         [254, 254, 254]]], shape=(640, 640, 3), dtype=uint8)
 orig_shape: (640, 640)
 path: 'd:\\research papers\\jenil_sir_project\\Counterfeit_med_detection.v4i.yolov8\\test\\images\\FDA-Advisory-No-2022-0611-25_png.rf.6f9b23d8c6fa5a8db3ac1558236f070f.jpg'
 probs: None
 save_dir: 'D:\\research papers\\jenil_sir_project\\Counterfeit_med_detection.v4i.yolov8\\runs\\detect\\crops_test'
 speed: {'preprocess': 1.5387000748887658, 'inference': 31.615399988368154, 'postprocess': 0.7081999210640788},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'authentic', 1: 'counterfeit'}
 obb: None
 orig_img: array([[[254, 254, 254],
         [254, 254, 254],
         [254, 254, 254],
         ...,
         [254, 254, 254],
         [254, 254, 254],
         [254, 254, 254]],

        [[254, 254, 254],
         [254, 254, 254],
         [254, 254, 254],
         ...,
         [254, 254, 254],
         [254, 254, 254],
         [254, 254, 254]],

        [[254, 254, 254],
         [254, 254, 254],
         [254, 254, 254],
         ...,
         [254, 254, 254],
         [254, 254, 254],
         [254, 254, 254]],

        ...,

        [[255, 255, 255],
         [254, 254, 254],
         [253, 253, 253],
         ...,
         [254, 254, 254],
         [254, 254, 254],
         [254, 254, 254]],

        [[251, 251, 251],
         [251, 251, 251],
         [251, 251, 251],
         ...,
         [254, 254, 254],
         [254, 254, 254],
         [254, 254, 254]],

        [[247, 247, 247],
         [248, 248, 248],
         [249, 249, 249],
         ...,
         [254, 254, 254],
         [254, 254, 254],
         [254, 254, 254]]], shape=(640, 640, 3), dtype=uint8)
 orig_shape: (640, 640)
 path: 'd:\\research papers\\jenil_sir_project\\Counterfeit_med_detection.v4i.yolov8\\test\\images\\FDA-Advisory-No-2022-0611-33_png.rf.eaa7a20d59cc5b710c425b064243dccd.jpg'
 probs: None
 save_dir: 'D:\\research papers\\jenil_sir_project\\Counterfeit_med_detection.v4i.yolov8\\runs\\detect\\crops_test'
 speed: {'preprocess': 1.1230000527575612, 'inference': 32.37139992415905, 'postprocess': 0.4887999966740608},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'authentic', 1: 'counterfeit'}
 obb: None
 orig_img: array([[[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        ...,

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]]], shape=(640, 640, 3), dtype=uint8)
 orig_shape: (640, 640)
 path: 'd:\\research papers\\jenil_sir_project\\Counterfeit_med_detection.v4i.yolov8\\test\\images\\How-to-spot-fake-biogesic-and-bioflu_jpg.rf.aa6360c8d0ffc4fab456e88f608c9fe8.jpg'
 probs: None
 save_dir: 'D:\\research papers\\jenil_sir_project\\Counterfeit_med_detection.v4i.yolov8\\runs\\detect\\crops_test'
 speed: {'preprocess': 1.0796000715345144, 'inference': 34.15229998063296, 'postprocess': 0.6488999351859093},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'authentic', 1: 'counterfeit'}
 obb: None
 orig_img: array([[[255, 255, 254],
         [255, 255, 254],
         [255, 255, 254],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 254],
         [255, 255, 254],
         [255, 255, 254],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 254],
         [255, 255, 254],
         [255, 255, 254],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        ...,

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,

In [36]:
results = model.val()
print(results.results_dict)

Ultralytics 8.4.15  Python-3.14.3 torch-2.10.0+cpu CPU (AMD Ryzen 7 7840HS w/ Radeon 780M Graphics)
val: Fast image access  (ping: 0.30.1 ms, read: 3.01.3 MB/s, size: 48.3 KB)
val: Scanning D:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\valid\labels.cache... 122 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 122/122 157.1Kit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 1.2it/s 6.5s0.8ss
                   all        122        240      0.721      0.855      0.809       0.63
             authentic        110        184      0.837      0.924      0.959      0.777
           counterfeit         15         56      0.604      0.786       0.66      0.484
Speed: 0.6ms preprocess, 29.0ms inference, 0.0ms loss, 0.7ms postprocess per image
Results saved to D:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\runs\detect\val7
{'metrics/precision(B)': 0.7205632728842438, 'metrics/recall(B)': 0.8549348291588019, 'metrics/mAP50(B)': 0.8093402767152553, 'metrics/mAP50-95(B)': 0.6301612229568315, 'fitness': 0.6301612229568315}

In [10]:
import os
import cv2
import numpy as np
import pandas as pd

# Path to cropped images
base_path = "runs/detect/crops_train/crops"

data = []

for class_name in os.listdir(base_path):
    class_path = os.path.join(base_path, class_name)
    
    for img_file in os.listdir(class_path):
        img_path = os.path.join(class_path, img_file)
        
        img = cv2.imread(img_path)
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        
        # Mean and Std for each channel
        mean = np.mean(img, axis=(0,1))
        std = np.std(img, axis=(0,1))
        
        features = [
            mean[0], mean[1], mean[2],   # R, G, B mean
            std[0], std[1], std[2],      # R, G, B std
        ]
        
        label = 0 if class_name == "authentic" else 1
        
        data.append(features + [label])

# Create DataFrame
columns = [
    "mean_R", "mean_G", "mean_B",
    "std_R", "std_G", "std_B",
    "label"
]

df_train = pd.DataFrame(data, columns=columns)

df_train.head()

       mean_R      mean_G      mean_B      std_R      std_G      std_B  label
0  165.537308  157.422370  151.679617  67.243783  76.557730  76.903178      0
1  173.706477  171.444073  160.501374  61.571259  62.022496  65.662154      0
2  155.764483  150.428218  142.869940  58.082626  63.396733  70.191645      0
3  146.495541  141.184268  133.994985  61.219778  66.778094  72.502819      0
4  207.717167  190.215065  132.335786  42.585231  53.738962  79.296688      0

In [28]:
import os
import cv2
import numpy as np
import pandas as pd

# Path to cropped images
base_path = "runs/detect/crops_test/crops"

data = []

for class_name in os.listdir(base_path):
    class_path = os.path.join(base_path, class_name)
    
    for img_file in os.listdir(class_path):
        img_path = os.path.join(class_path, img_file)
        
        img = cv2.imread(img_path)
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        
        # Mean and Std for each channel
        mean = np.mean(img, axis=(0,1))
        std = np.std(img, axis=(0,1))
        
        features = [
            mean[0], mean[1], mean[2],   # R, G, B mean
            std[0], std[1], std[2],      # R, G, B std
        ]
        
        label = 0 if class_name == "authentic" else 1
        
        data.append(features + [label])

# Create DataFrame
columns = [
    "mean_R", "mean_G", "mean_B",
    "std_R", "std_G", "std_B",
    "label"
]

df_test = pd.DataFrame(data, columns=columns)

df_test.head()

       mean_R      mean_G      mean_B      std_R      std_G      std_B  label
0  211.376186  216.367069  211.352771  61.684148  41.691629  39.787575      0
1  238.242563  105.953514   92.677703  27.738769  89.350810  95.865120      0
2  198.129320  193.847729  193.873910  50.596560  50.836713  43.366479      0
3  241.309263  100.098466   85.961757  27.362277  92.119623  99.884476      0
4  171.794535  160.475092  147.244912  55.189320  59.090234  68.215390      0

In [29]:
from skimage.feature import graycomatrix, graycoprops
import os
import cv2
import pandas as pd

# ================= TRAIN TEXTURE =================
base_path = "runs/detect/crops_train/crops"

texture_data = []

for class_name in os.listdir(base_path):
    class_path = os.path.join(base_path, class_name)
    
    for img_file in os.listdir(class_path):
        img_path = os.path.join(class_path, img_file)
        
        img = cv2.imread(img_path)
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        gray = cv2.resize(gray, (256, 256))
        
        glcm = graycomatrix(gray, distances=[1], angles=[0], levels=256, symmetric=True, normed=True)
        
        contrast = graycoprops(glcm, 'contrast')[0, 0]
        energy = graycoprops(glcm, 'energy')[0, 0]
        homogeneity = graycoprops(glcm, 'homogeneity')[0, 0]
        correlation = graycoprops(glcm, 'correlation')[0, 0]
        
        label = 0 if class_name == "authentic" else 1
        
        texture_data.append([contrast, energy, homogeneity, correlation, label])

texture_train = pd.DataFrame(texture_data, columns=["contrast","energy","homogeneity","correlation","label"])


# ================= TEST TEXTURE =================
base_path = "runs/detect/crops_test/crops"

texture_data = []

for class_name in os.listdir(base_path):
    class_path = os.path.join(base_path, class_name)
    
    for img_file in os.listdir(class_path):
        img_path = os.path.join(class_path, img_file)
        
        img = cv2.imread(img_path)
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        gray = cv2.resize(gray, (256, 256))
        
        glcm = graycomatrix(gray, distances=[1], angles=[0], levels=256, symmetric=True, normed=True)
        
        contrast = graycoprops(glcm, 'contrast')[0, 0]
        energy = graycoprops(glcm, 'energy')[0, 0]
        homogeneity = graycoprops(glcm, 'homogeneity')[0, 0]
        correlation = graycoprops(glcm, 'correlation')[0, 0]
        
        label = 0 if class_name == "authentic" else 1
        
        texture_data.append([contrast, energy, homogeneity, correlation, label])

texture_test = pd.DataFrame(texture_data, columns=["contrast","energy","homogeneity","correlation","label"])

In [30]:
import os
import cv2
import pandas as pd

# ================= TRAIN SHAPE =================
base_path = "runs/detect/crops_train/crops"

shape_data = []

for class_name in os.listdir(base_path):
    class_path = os.path.join(base_path, class_name)
    
    for img_file in os.listdir(class_path):
        img_path = os.path.join(class_path, img_file)
        
        img = cv2.imread(img_path)
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        
        _, thresh = cv2.threshold(gray, 127, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)
        contours, _ = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        
        if len(contours) > 0:
            cnt = max(contours, key=cv2.contourArea)
            area = cv2.contourArea(cnt)
            perimeter = cv2.arcLength(cnt, True)
            x, y, w, h = cv2.boundingRect(cnt)
            aspect_ratio = float(w) / h if h != 0 else 0
        else:
            area = 0
            perimeter = 0
            aspect_ratio = 0
        
        label = 0 if class_name == "authentic" else 1
        
        shape_data.append([area, perimeter, aspect_ratio, label])

shape_train = pd.DataFrame(shape_data, columns=["area","perimeter","aspect_ratio","label"])


# ================= TEST SHAPE =================
base_path = "runs/detect/crops_test/crops"

shape_data = []

for class_name in os.listdir(base_path):
    class_path = os.path.join(base_path, class_name)
    
    for img_file in os.listdir(class_path):
        img_path = os.path.join(class_path, img_file)
        
        img = cv2.imread(img_path)
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        
        _, thresh = cv2.threshold(gray, 127, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)
        contours, _ = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        
        if len(contours) > 0:
            cnt = max(contours, key=cv2.contourArea)
            area = cv2.contourArea(cnt)
            perimeter = cv2.arcLength(cnt, True)
            x, y, w, h = cv2.boundingRect(cnt)
            aspect_ratio = float(w) / h if h != 0 else 0
        else:
            area = 0
            perimeter = 0
            aspect_ratio = 0
        
        label = 0 if class_name == "authentic" else 1
        
        shape_data.append([area, perimeter, aspect_ratio, label])

shape_test = pd.DataFrame(shape_data, columns=["area","perimeter","aspect_ratio","label"])

In [41]:
# ================= FINAL TRAIN =================
final_train_df = pd.concat(
    [df_train.drop(columns=["label"]),
     texture_train.drop(columns=["label"]),
     shape_train.drop(columns=["label"]),
     df_train["label"]],
    axis=1
)

# ================= FINAL TEST =================
final_test_df = pd.concat(
    [df_test.drop(columns=["label"]),
     texture_test.drop(columns=["label"]),
     shape_test.drop(columns=["label"]),
     df_test["label"]],
    axis=1
)

print(final_train_df.head())
print(final_test_df.head())

       mean_R      mean_G      mean_B      std_R      std_G      std_B  \
0  165.537308  157.422370  151.679617  67.243783  76.557730  76.903178
1  173.706477  171.444073  160.501374  61.571259  62.022496  65.662154
2  155.764483  150.428218  142.869940  58.082626  63.396733  70.191645
3  146.495541  141.184268  133.994985  61.219778  66.778094  72.502819
4  207.717167  190.215065  132.335786  42.585231  53.738962  79.296688

     contrast    energy  homogeneity  correlation     area    perimeter  \
0   50.951057  0.080443     0.383521     0.995102    544.5    98.669047
1   77.594868  0.063993     0.291203     0.989483  17720.5  1023.761534
2  148.684467  0.117271     0.526677     0.979262  56716.5   969.438599
3  155.897411  0.118840     0.523561     0.980502  56746.5   970.267026
4   15.552344  0.104274     0.539586     0.997120   7903.5   512.551296

   aspect_ratio  label
0      1.590909      0
1      0.384615      0
2      0.967611      0
3      0.967611      0
4      0.333333      0
       mean_R      mean_G      mean_B      std_R      std_G      std_B  \
0  211.376186  216.367069  211.352771  61.684148  41.691629  39.787575
1  238.242563  105.953514   92.677703  27.738769  89.350810  95.865120
2  198.129320  193.847729  193.873910  50.596560  50.836713  43.366479
3  241.309263  100.098466   85.961757  27.362277  92.119623  99.884476
4  171.794535  160.475092  147.244912  55.189320  59.090234  68.215390

      contrast    energy  homogeneity  correlation      area    perimeter  \
0   321.098560  0.160001     0.573459     0.920182    6239.5  1016.409161
1  1100.912531  0.193354     0.418631     0.868909  118449.0  1800.274166
2   102.162561  0.066402     0.523541     0.978492    3602.5   286.041630
3  1706.382675  0.377606     0.570976     0.803324  118106.5  1753.026473
4   202.023897  0.134160     0.333586     0.967959  112938.0  1723.518894

   aspect_ratio  label
0      1.025974      0
1      3.121951      0
2      3.323529      0
3      3.137255      0
4      0.400369      0

In [42]:
print("Total samples:", len(final_train_df))
print("Total features (including label):", final_train_df.shape[1])

Total samples: 8322
Total features (including label): 14

In [43]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# Separate features and label
X = final_train_df.drop(columns=["label"])
y = final_train_df["label"]

# Train-test split (important)
# TRAIN DATA
X_train = final_train_df.drop(columns=["label"])
y_train = final_train_df["label"]

# TEST DATA
X_test = final_test_df.drop(columns=["label"])
y_test = final_test_df["label"]

# Normalize features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Training samples:", X_train_scaled.shape) 
print("Testing samples:", X_test_scaled.shape)

print("Train samples:", len(final_train_df))
print("Test samples:", len(final_test_df))

Training samples: (8322, 13)
Testing samples: (180, 13)
Train samples: 8322
Test samples: 180

In [44]:
print(final_train_df.shape)
print(final_test_df.shape)

(8322, 14)
(180, 14)

In [45]:
print(final_train_df.head(2))
print(final_test_df.head(2))

       mean_R      mean_G      mean_B      std_R      std_G      std_B  \
0  165.537308  157.422370  151.679617  67.243783  76.557730  76.903178
1  173.706477  171.444073  160.501374  61.571259  62.022496  65.662154

    contrast    energy  homogeneity  correlation     area    perimeter  \
0  50.951057  0.080443     0.383521     0.995102    544.5    98.669047
1  77.594868  0.063993     0.291203     0.989483  17720.5  1023.761534

   aspect_ratio  label
0      1.590909      0
1      0.384615      0
       mean_R      mean_G      mean_B      std_R      std_G      std_B  \
0  211.376186  216.367069  211.352771  61.684148  41.691629  39.787575
1  238.242563  105.953514   92.677703  27.738769  89.350810  95.865120

      contrast    energy  homogeneity  correlation      area    perimeter  \
0   321.098560  0.160001     0.573459     0.920182    6239.5  1016.409161
1  1100.912531  0.193354     0.418631     0.868909  118449.0  1800.274166

   aspect_ratio  label
0      1.025974      0
1      3.121951      0

In [47]:
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier

# ================= SPLIT =================
X_train = final_train_df.drop(columns=["label"])
y_train = final_train_df["label"]

X_test = final_test_df.drop(columns=["label"])
y_test = final_test_df["label"]

# ================= SCALE =================
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# ================= MODEL =================
model = RandomForestClassifier(
    n_estimators=200,
    max_depth=10,
    min_samples_split=5,
    class_weight={0:1, 1:2},  # 🔥 increase weight for counterfeit
    random_state=42
)
model.fit(X_train_scaled, y_train)

# ================= PREDICT =================
y_pred = model.predict(X_test_scaled)

# ================= RESULTS =================
print("Classification Report:\n")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, y_pred))

Classification Report:

              precision    recall  f1-score   support

           0       0.84      0.91      0.87       119
           1       0.78      0.66      0.71        61

    accuracy                           0.82       180
   macro avg       0.81      0.78      0.79       180
weighted avg       0.82      0.82      0.82       180


Confusion Matrix:

[[108  11]
 [ 21  40]]

In [50]:
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Create SVM model
svm_model = SVC(
    kernel='rbf',
    C=5,                     # ↓ reduce overfitting
    gamma=0.1,               # 🔥 more flexible boundary
    class_weight={0:1, 1:2}, # 🔥 push counterfeit detection
    probability=True         # needed for next improvement
)

# Train
svm_model.fit(X_train_scaled, y_train)

# Predict
y_pred = svm_model.predict(X_test_scaled)

# Evaluate
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.8555555555555555

Classification Report:

              precision    recall  f1-score   support

           0       0.90      0.87      0.89       119
           1       0.77      0.82      0.79        61

    accuracy                           0.86       180
   macro avg       0.84      0.85      0.84       180
weighted avg       0.86      0.86      0.86       180


Confusion Matrix:

[[104  15]
 [ 11  50]]

In [64]:
import joblib

joblib.dump(svm_model, "svm_model.pkl")
joblib.dump(scaler, "scaler.pkl")

['scaler.pkl']

In [102]:
from xgboost import XGBClassifier

xgb_model = XGBClassifier(
    n_estimators=500,        # more trees
    max_depth=5,             # prevent overfit
    learning_rate=0.03,      # slower learning = better
    scale_pos_weight=8,      # 🔥 push counterfeit detection
    subsample=0.9,
    colsample_bytree=0.9,
    random_state=42
)

xgb_model.fit(X_train_scaled, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.9, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.03, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=500,
              n_jobs=None, num_parallel_tree=None, ...)

In [108]:
import cv2
import numpy as np
import joblib
from ultralytics import YOLO
from skimage.feature import graycomatrix, graycoprops

# -----------------------------
# Load trained models
# -----------------------------
yolo_model = YOLO("runs/detect/train13/weights/best.pt")
svm_model = joblib.load("svm_model.pkl")
scaler = joblib.load("scaler.pkl")

# -----------------------------
# Function to extract features
# -----------------------------
def extract_features(img):

    # ----- COLOR FEATURES -----
    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    mean = np.mean(img_rgb, axis=(0,1))
    std = np.std(img_rgb, axis=(0,1))

    # ----- TEXTURE FEATURES -----
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    gray = cv2.resize(gray, (256, 256))

    glcm = graycomatrix(gray,
                        distances=[1],
                        angles=[0],
                        levels=256,
                        symmetric=True,
                        normed=True)

    contrast = graycoprops(glcm, 'contrast')[0, 0]
    energy = graycoprops(glcm, 'energy')[0, 0]
    homogeneity = graycoprops(glcm, 'homogeneity')[0, 0]
    correlation = graycoprops(glcm, 'correlation')[0, 0]

    # ----- SHAPE FEATURES -----
    _, thresh = cv2.threshold(gray, 127, 255,
                              cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)

    contours, _ = cv2.findContours(thresh,
                                   cv2.RETR_EXTERNAL,
                                   cv2.CHAIN_APPROX_SIMPLE)

    if len(contours) > 0:
        cnt = max(contours, key=cv2.contourArea)
        area = cv2.contourArea(cnt)
        perimeter = cv2.arcLength(cnt, True)
        x, y, w, h = cv2.boundingRect(cnt)
        aspect_ratio = float(w) / h if h != 0 else 0
    else:
        area = 0
        perimeter = 0
        aspect_ratio = 0

    features = [
        mean[0], mean[1], mean[2],
        std[0], std[1], std[2],
        contrast, energy, homogeneity, correlation,
        area, perimeter, aspect_ratio
    ]

    return np.array(features).reshape(1, -1)


# -----------------------------
# Predict Function
# -----------------------------
def predict_image(image_path):

    # Step 1: YOLO detection
    results = yolo_model(image_path)

    if len(results[0].boxes) == 0:
        print("No medicine detected.")
        return

    # Take first detected box
    box = results[0].boxes.xyxy[0].cpu().numpy().astype(int)

    img = cv2.imread(image_path)
    crop = img[box[1]:box[3], box[0]:box[2]]

    # Step 2: Extract features
    features = extract_features(crop)

    # Step 3: Scale features
    features_scaled = scaler.transform(features)

    # Step 4: Predict
    prob = xgb_model.predict_proba(features_scaled)[0]

    prediction = 1 if prob[1] > 0.30 else 0
    confidence = prob[prediction]

    if prediction == 0:
        print("Prediction: AUTHENTIC")
    else:
        print("Prediction: COUNTERFEIT")

    print("Confidence score:", confidence)

predict_image("./ind_test/fake1.jpg")

image 1/1 d:\research papers\jenil_sir_project\Counterfeit_med_detection.v4i.yolov8\ind_test\fake1.jpg: 416x352 1 authentic, 41.4ms
Speed: 2.0ms preprocess, 41.4ms inference, 0.9ms postprocess per image at shape (1, 3, 416, 352)
Prediction: AUTHENTIC
Confidence score: 0.9891131

c:\Users\HP\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [85]:
from xgboost import XGBClassifier
from sklearn.metrics import classification_report, confusion_matrix

xgb_model = XGBClassifier(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.05,
    scale_pos_weight=6,  # IMPORTANT (imbalance handling)
    random_state=42
)

xgb_model.fit(X_train_scaled, y_train)

y_pred = xgb_model.predict(X_test_scaled)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.89      0.87      0.88       119
           1       0.76      0.79      0.77        61

    accuracy                           0.84       180
   macro avg       0.83      0.83      0.83       180
weighted avg       0.85      0.84      0.85       180

[[104  15]
 [ 13  48]]

In [ ]:
scale_pos_weight = 1443 / 222   # ≈ 6.5

In [ ]:
from xgboost import XGBClassifier

model = XGBClassifier(
    scale_pos_weight=6.5,
    random_state=42,
    use_label_encoder=False,
    eval_metric='logloss'
)

In [ ]:
from sklearn.model_selection import RandomizedSearchCV

param_dist = {
    'n_estimators': [100, 200, 300, 500],
    'max_depth': [3, 5, 7, 10],
    'learning_rate': [0.01, 0.05, 0.1, 0.2],
    'subsample': [0.7, 0.8, 1.0],
    'colsample_bytree': [0.7, 0.8, 1.0],
    'gamma': [0, 0.1, 0.3, 0.5],
    'min_child_weight': [1, 3, 5]
}

search = RandomizedSearchCV(
    estimator=model,
    param_distributions=param_dist,
    n_iter=30,
    scoring='f1',   # IMPORTANT: focus on F1
    cv=5,
    verbose=2,
    n_jobs=-1
)

search.fit(X_train, y_train)

best_model = search.best_estimator_

In [ ]:
y_probs = best_model.predict_proba(X_test)[:, 1]

import numpy as np
from sklearn.metrics import f1_score

best_thresh = 0
best_f1 = 0

for t in np.arange(0.1, 0.9, 0.05):
    y_pred = (y_probs > t).astype(int)
    f1 = f1_score(y_test, y_pred)
    
    if f1 > best_f1:
        best_f1 = f1
        best_thresh = t

print("Best Threshold:", best_thresh)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix

y_pred = (y_probs > best_thresh).astype(int)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

In [ ]:
from xgboost import XGBClassifier

# Calculate class weight
scale_pos_weight = 1443 / 222   # use your actual values

model = XGBClassifier(
    n_estimators=200,
    max_depth=5,
    learning_rate=0.1,
    subsample=0.8,
    colsample_bytree=0.8,
    scale_pos_weight=scale_pos_weight,  # IMPORTANT
    random_state=42,
    use_label_encoder=False,
    eval_metric='logloss'
)

In [ ]:
model.fit(X_train, y_train)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix

y_pred = model.predict(X_test)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))